### PR TITLE
Pre commit

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Comment by pietrushnic** [comment]
@macpijan can we somehow enforce the rule that remark-tempaltes and img is in the root directory? So links for images as well as link for any component in remark have to start with `/` ?

**Comment by macpijan** [comment]
@pietrushnic If we can create a script or shell expression to check for that, then we could use custom hook like this: https://github.com/Dasharo/ec/blob/master/.pre-commit-config.yaml#L51

**Comment by pietrushnic** [comment]
The following command detect if any file has stuff we don't like

```
grep -E '"remark|"images|\(images|\(img|"img' . --include='*.md' -r
```

**Comment by macpijan** [comment]
@pietrushnic please check: 45b9d9e3123a3444481498c10a2a819f000a3627

**Comment by macpijan** [comment]
Output right now:

```
t
macpijan in ~/projects/github/3mdeb/conferences on pre-commit λ pre-commit run --all-files                                  
check for added large files.........................................................................Passed
check for merge conflicts...........................................................................Passed
check for broken symlinks.......................................................(no files to check)Skipped
detect private key..................................................................................Passed
fix end of files....................................................................................Passed
trim trailing whitespace............................................................................Passed
mixed line ending...................................................................................Passed
codespell...........................................................................................Passed
markdownlint........................................................................................Passed
markdownlint-fix....................................................................................Passed
ShellCheck v0.9.0...................................................................................Passed
Checks if the remark-templates and static content is placed in root directory.......................Failed
- hook id: remark-root-dir
- exit code: 1

No problematic lines found in: README.md
No problematic lines found in: 2023/YoctoDevDay/introduction-to-openbmc.md
9:<img src="remark-templates/3mdeb-presentation-template/images/logo.png"
17:  src="remark-templates/3mdeb-presentation-template/images/maciej_pijanowski.png"
33:  src="remark-templates/3mdeb-presentation-template/images/twitter.png"
36:  src="remark-templates/3mdeb-presentation-template/images/email.png"
40:  src="remark-templates/3mdeb-presentation-template/images/linkedin.png"
75:.center[.image-80[![](img/ast2500_app.jpg)]]
107:.center[.image-35[![](img/OpenBMC_logo.png)]]
130:.center[.image-40[![](img/confusedtravolta.jpg)]]
168:.center[.image-90[![](img/openbmc_vue_overview.png)]]
183:.center[.image-90[![](img/openbmc_events.png)]]
197:.center[.image-90[![](img/openbmc_sensors.png)]]
209:.center[.image-90[![](img/openbmc_power_control.png)]]
221:.center[.image-90[![](img/openbmc_sol.png)]]
236:.center[.image-90[![](img/openbmc_kvm.png)]]
248:.center[.image-90[![](img/openbmc_virtual_media.png)]]
269:.center[.image-90[![](img/openbmc_firmware_update.png)]]
298:.center[.image-30[![](img/DMTF_Redfish_logo_R.jpg)]]
392:.center[.image-30[![](img/openbmc_layers.png)]]
444:.center[.image-35[![](img/X11SSH-TF.webp)]]
577:- <a href="mailto:contact@3mdeb.com"><img src="remark-templates/3mdeb-presentation-template/images/email.png" width="24px" style="margin-bottom:-5px; margin-left:-15px"/> contact@3mdeb.com</a>
579:- <a href="https://www.facebook.com/3mdeb"><img src="remark-templates/3mdeb-presentation-template/images/facebook.png" width="24px" style="margin-bottom:-5px; margin-left:-15px"/> facebook.com/3mdeb</a>
581:- <a href="https://twitter.com/3mdeb_com"><img src="remark-templates/3mdeb-presentation-template/images/twitter.png" width="24px" style="margin-bottom:-5px; margin-left:-15px"/> @3mdeb_com</a>
583:- <a href="https://www.linkedin.com/company/3mdeb"><img src="remark-templates/3mdeb-presentation-template/images/linkedin.png" width="24px" style="margin-bottom:-5px; margin-left:-15px"/> linkedin.com/company/3mdeb</a>
Found problematic lines in: unveiling-openbmc.md
See above for line numbers
No problematic lines found in: 2019/OSFC/README.md
No problematic lines found in: 2019/LPC/README.md
```

**Comment by pietrushnic** [comment]
@macpijan I guess introducing GH action for automatic change is another topic?
It seems you fixed all files to point to root dir, can you past pre-commit check - I will approve and merge based on that.

**Comment by macpijan** [comment]
CI passed, so merging.

**Pull request merged**
