### PR TITLE
Securing Embedded Systems with fTPM implemented as Trusted Application in TEE

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by pietrushnic** [comment]
@tym2k1, it doesn't look like it has the most recent version of the slides. Also, your signature is not verified; please fix your gpg and git configuration.

**Comment by tym2k1** [comment]
This is the final version that was presented at [FOSDEM 2024](https://fosdem.org/2024/schedule/event/fosdem-2024-3097-securing-embedded-systems-with-ftpm-implemented-as-trusted-application-in-tee/). The pre-commit fails as it tries to check the grammar of an svg file, treats the second name of one of the authors listed in resources as a misspelling and doesn't allow for headers to be longer than 80 characters. I've used headers as a way to change font size and style to highlight certain information at some slides and reduce the font-size of resources so they can be accomodated at one slide. Should i fix it or leave it as it is?

**Comment by pietrushnic** [comment]
@tym2k1 of course you have to fix it, but ideally in a way that will not change the way your presentation look. You can suppress some errors if there is clear problem with how pre-commit interpret some parts as issues, but this should be last resort.

I'm pretty sure you can add Fo to some dictionary, or suppress this check for this svg file. 
That looks like typo which you should fix:
```
2024/FOSDEM/fptm_ta_tee/fosdem2024_ftpm_ta_tee.md:467: Challener ==> Challenger
```

**Comment by macpijan** [comment]
I have added svg to be exluded, so if you rebase it shall be fixed: https://github.com/3mdeb/conferences/blob/master/.pre-commit-config.yaml#L12

**Pull request merged**
