### PR TITLE
CfP: Securing Embedded Systems with fTPM implemented as Trusted Application in TEE

### PR DESCRIPTION
**Pull request by TomaszAIR**
This pull request contains expanded README description and cfp for fTPM in TEE

### CODE REVIEW

**Comment by pietrushnic** [comment]
What conference do we target?

**Comment by pietrushnic** [comment]
@TomaszAIR @macpijan was that CfP ever sent?

**Comment by TomaszAIR** [comment]
@pietrushnic no, it was not sent. The CFP was created to use in the future. I think we could try to present this on FOSDEM.

**Comment by pietrushnic** [comment]
@TomaszAIR let's do it.

**Comment by TomaszAIR** [comment]
Merging this

**Pull request closed without merging**
